### ISSUE TITLE
No sites load

### ISSUE THREAD

**Issue by om3ga6400** [ading2210/sandstone#2]
Error message:

An unexpected error has occurred
TypeError: Request failed with error code 7: Could not connect to server
    at D (file:///home/chronos/u-dad372cb6ec8ba43057e9db829d34115675e0a87/MyFiles/Downloads/sandstone.html:97:2094127)
    at Object.R [as end] (file:///home/chronos/u-dad372cb6ec8ba43057e9db829d34115675e0a87/MyFiles/Downloads/sandstone.html:97:2093231)
    at sI.end_callback (file:///home/chronos/u-dad372cb6ec8ba43057e9db829d34115675e0a87/MyFiles/Downloads/sandstone.html:97:2091622)
    at file:///home/chronos/u-dad372cb6ec8ba43057e9db829d34115675e0a87/MyFiles/Downloads/sandstone.html:97:2091159
    at wasm://wasm/005aff36:wasm-function[2099]:0xce2b2
    at file:///home/chronos/u-dad372cb6ec8ba43057e9db829d34115675e0a87/MyFiles/Downloads/sandstone.html:97:12738
    at sI.event_loop_func (file:///home/chronos/u-dad372cb6ec8ba43057e9db829d34115675e0a87/MyFiles/Downloads/sandstone.html:97:2092599)
    at file:///home/chronos/u-dad372cb6ec8ba43057e9db829d34115675e0a87/MyFiles/Downloads/sandstone.html:97:2092514
Sandstone v0.1.1 (c1cdd70)

**Comment by ading2210** [comment]
It looks like the Wisp server is being blocked by your network here. Could you try other wisp servers to see if they work? And does it work if you are connected to a mobile hotspot or home network?

**Comment by om3ga6400** [comment]
what are some other wisp servers?

**Comment by ading2210** [comment]
Try some of these:
- `wss://anura.pro/`
- `wss://aluu.xyz/
- `wss://puter.cafe`

**Comment by om3ga6400** [comment]
just reopend sandstone again today and the original works now and so do all the others

**Comment by nobody81754** [comment]
all of the wisp servers are blocked for me

**Comment by Airbus-A330-bruh** [comment]
wifi block? use blobwifi

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by nobody81754** [comment]
Please ading2210, i need this! My proxy kinda wispless.

**Comment by om3ga6400** [comment]
> Please ading2210, i need this! My proxy kinda wispless.

ts is dead, doubt u will get help

**Comment by Airbus-A330-bruh** [comment]
> Please ading2210, i need this! My proxy kinda wispless.

lol

**Comment by nobody81754** [comment]
Ok i actually need a wisp server

**Comment by Airbus-A330-bruh** [comment]
> Ok, i actually need a wisp server

just use a vpn bruh look up blobby boi

**Comment by nobody81754** [comment]
my school is not that dumb b
